tasks:
  - name: Install Python
    init: pyenv install 3.10.7
    command: pyenv global 3.10.7
  - name: Install Sandbox
    init: git clone https://github.com/algorand/sandbox
  - name: Start Sandbox
    before: cd /workspace/Workshop-GettingStarted/sandbox 
    command: ./sandbox up dev -v
ports:
  - port: 4001
  - port: 4002
  - port: 8980
